apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: appuser-gateway-traefik-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: appuser-gateway-traefik-app-user
    k8s.kuboard.cn/workload: appuser-gateway-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-appuser-gateway-prefix@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/appuser/v1/signup
            backend:
              serviceName: appuser-gateway
              servicePort: 50500
          - path: /api/appuser/v1/get/app
            backend:
              serviceName: appuser-gateway
              servicePort: 50500
          - path: /api/appuser/v1/login
            backend:
              serviceName: appuser-gateway
              servicePort: 50500
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: appuser-gateway-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: appuser-gateway-traefik-app-user
    k8s.kuboard.cn/workload: appuser-gateway-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-appuser-gateway-prefix@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/appuser/v1/update/user
            backend:
              serviceName: appuser-gateway
              servicePort: 50500
          - path: /api/appuser/v1/logout
            backend:
              serviceName: appuser-gateway
              servicePort: 50500
          - path: /api/appuser/v1/logined
            backend:
              serviceName: appuser-gateway
              servicePort: 50500
          - path: /api/appuser/v1/get
            backend:
              serviceName: appuser-gateway
              servicePort: 50500
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
